name: MERN Stack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js for frontend
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'npm'
    - run: npm ci --prefix studyNotion
    - run: npm test --prefix studyNotion

  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js for backend
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'npm'
    - run: npm ci --prefix studnot_backend
    - run: npm test --prefix studnot_backend
